#!/usr/bin/env python3
"""Generate reproducible, synthetic PCAPNG fixtures for SecureMailScope."""

import argparse
import hashlib
import json
import sys
from pathlib import Path
from scapy.utils import PcapNgWriter

from pcap_generator.scenarios import SCENARIO_BUILDERS


def generate_scenario(name: str, output_dir: Path, seed: int = 42) -> dict:
    """Generate a single scenario PCAPNG file and return its manifest metadata."""
    if name not in SCENARIO_BUILDERS:
        raise ValueError(f"Unknown scenario: {name}. Available: {list(SCENARIO_BUILDERS.keys())}")

    builder = SCENARIO_BUILDERS[name]
    packets, meta = builder(seed=seed)

    filename = f"{name}.pcapng"
    pcap_path = output_dir / filename

    # Write using Scapy's PcapNgWriter
    with PcapNgWriter(str(pcap_path)) as writer:
        for pkt in packets:
            # Force checksum recalculation
            if "IP" in pkt:
                del pkt["IP"].chksum
            if "TCP" in pkt:
                del pkt["TCP"].chksum
            writer.write(pkt)

    # Compute SHA-256 hash and file size
    with open(pcap_path, "rb") as f:
        file_bytes = f.read()
        sha256 = hashlib.sha256(file_bytes).hexdigest()

    meta["filename"] = filename
    meta["pcap_path"] = str(pcap_path.relative_to(output_dir.parent) if output_dir.parent == Path.cwd() else pcap_path)
    meta["packet_count"] = len(packets)
    meta["sha256"] = sha256
    meta["size_bytes"] = len(file_bytes)
    meta["provenance"] = "Synthetic wire-format laboratory fixture generated by SecureMailScope generator"

    return meta


def main():
    parser = argparse.ArgumentParser(description="Generate synthetic PCAPNG fixtures for SecureMailScope.")
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=Path("captures"),
        help="Target directory for generated PCAPNG files and manifest.json (default: captures)",
    )
    parser.add_argument(
        "--seed",
        "-s",
        type=int,
        default=42,
        help="Random seed for deterministic generation (default: 42)",
    )
    parser.add_argument(
        "--scenarios",
        nargs="*",
        default=list(SCENARIO_BUILDERS.keys()),
        help="List of scenarios to generate (default: all)",
    )
    args = parser.parse_args()

    args.output.mkdir(parents=True, exist_ok=True)
    manifest = []

    print(f"[*] Generating {len(args.scenarios)} PCAPNG scenario fixtures in '{args.output}' (seed={args.seed})...\n")
    print(f"{'Scenario':<25} {'Packets':<8} {'Size (B)':<10} {'Expected Severity':<18} {'SHA-256 (prefix)':<18}")
    print("-" * 85)

    for scenario_name in args.scenarios:
        meta = generate_scenario(scenario_name, args.output, seed=args.seed)
        manifest.append(meta)
        sha_prefix = meta["sha256"][:16] + "..."
        print(f"{scenario_name:<25} {meta['packet_count']:<8} {meta['size_bytes']:<10} {meta['expected_severity']:<18} {sha_prefix:<18}")

    manifest_path = args.output / "manifest.json"
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    print("-" * 85)
    print(f"[+] Successfully wrote {len(manifest)} PCAPNG files and manifest to: {manifest_path.resolve()}\n")


if __name__ == "__main__":
    main()
